# Generated by Django 4.1.2 on 2022-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [

    ]
