# Generated by Django 4.1.2 on 2022-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile-icon.jpg', upload_to='profile_pics/'),
        ),
    ]
