# Generated by Django 4.1.2 on 2022-12-17 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
