# Generated by Django 4.1.2 on 2022-12-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_child_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_children',
        ),
        migrations.AddField(
            model_name='appuser',
            name='number_of_children',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
