# Generated by Django 4.1.2 on 2023-07-20 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='number_of_children',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
