# Generated by Django 4.1.2 on 2023-08-10 12:25

import baby_food.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_child_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[baby_food.common.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[baby_food.common.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[baby_food.common.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[baby_food.common.validators.validate_name]),
        ),
    ]
