# Generated by Django 4.1.2 on 2023-08-13 11:17

import baby_food.common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0008_alter_gallery_options'),
        ('menus', '0008_remove_menu_name'),
        ('accounts', '0017_alter_child_first_name_alter_child_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, error_messages={'wrong amount': 'The orders amount must be more than 3 BGN'}, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),

    ]
