# Generated by Django 4.1.2 on 2023-08-13 11:18

import baby_food.common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_remove_menu_name'),
        ('orders', '0001_order'),
    ]

    operations = [

        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=3.5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('address', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menu')),
            ],
            options={
                'ordering': ['-product__date'],
            },
        ),
    ]
