# Generated by Django 4.1.2 on 2023-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
