# Generated by Django 4.1.2 on 2023-01-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_location_address_location_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
