# Generated by Django 4.1.2 on 2023-01-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
