# Generated by Django 4.1.2 on 2023-08-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-upload_date'], 'verbose_name_plural': 'Gallery'},
        ),
    ]
