# Generated by Django 4.1.2 on 2022-11-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
