# Generated by Django 4.1.2 on 2022-11-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0003_alter_recipewithoutallergens_options'),
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuWithoutAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.CharField(choices=[('10M-18M', '10M-18M'), ('18M-36M', '18M-36M')], max_length=10)),
                ('price', models.PositiveIntegerField(default=3.0, editable=False)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_dessert', to='recipes.recipewithoutallergens')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_main_dish', to='recipes.recipewithoutallergens')),
                ('soup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_soup', to='recipes.recipewithoutallergens')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.CharField(choices=[('10M-18M', '10M-18M'), ('18M-36M', '18M-36M')], max_length=10)),
                ('price', models.PositiveIntegerField(default=3.0, editable=False)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_dessert', to='recipes.recipe')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_main_dish', to='recipes.recipe')),
                ('soup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_soup', to='recipes.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
