# Generated by Django 4.1.2 on 2022-12-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipewithoutallergens'),
        ('menu_app', '0002_create_modul_Menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuWithoutAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField(default=3.0, editable=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('age', models.CharField(choices=[('10M-36M', '10M-36M')], max_length=10)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_dessert', to='recipes.recipewithoutallergens')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_main_dish', to='recipes.recipewithoutallergens')),
                ('soup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_soup', to='recipes.recipewithoutallergens')),
            ],
            options={
                'verbose_name_plural': 'Menu Without Allergens',
            },
        ),
    ]
