# Generated by Django 4.1.2 on 2022-11-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_create_models_menu_menuwithoutallergens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuwithoutallergens',
            options={'verbose_name_plural': 'Menu Without Allergens'},
        ),
    ]
