# Generated by Django 4.1.2 on 2022-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_menuwithoutallergens_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuwithoutallergens',
            name='age',
            field=models.CharField(choices=[('10M-36M', '10M-36M')], max_length=10),
        ),
    ]
