# Generated by Django 4.1.2 on 2023-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_menu_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(default=3.5, editable=False),
        ),
    ]
