# Generated by Django 4.1.2 on 2022-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_menuwithoutallergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='menuwithoutallergens',
            name='quantity',
        ),
    ]
