# Generated by Django 4.1.2 on 2022-12-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipewithoutallergens_allergens'),
        ('menu_app', '0004_remove_menu_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuwithoutallergens',
            name='main_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_main_dish', to='recipes.recipewithoutallergens', verbose_name='MAIN DISH'),
        ),
    ]
