# Generated by Django 4.1.2 on 2022-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_alter_menuwithoutallergens_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menuwithoutallergens',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
