# Generated by Django 4.1.2 on 2022-12-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_dish_type_and_more'),
        ('menu_app', '0005_alter_menuwithoutallergens_main_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='main_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_main_dish', to='recipes.recipe', verbose_name='main dish'),
        ),
        migrations.AlterField(
            model_name='menuwithoutallergens',
            name='main_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_wa_main_dish', to='recipes.recipewithoutallergens', verbose_name='main dish'),
        ),
    ]
