# Generated by Django 4.1.2 on 2023-08-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0007_alter_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
