# Generated by Django 4.1.2 on 2023-01-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('Allergy-Free Menu', 'Allergy-Free MENU'), ('Menu With Allergens', 'Menu With Allergens')], default='Allergy-Free Menu', max_length=30),
            preserve_default=False,
        ),
    ]
