# Generated by Django 4.1.2 on 2023-07-07 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0007_alter_category_options'),
        ('menus', '0007_alter_menu_price'),
        ('accounts', '0011_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, error_messages={'wrong amount': 'The order amount must be more than 3 BGN'}, max_digits=6)),
                ('paid', models.BooleanField(default=True)),
                ('payment_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),

    ]
