# Generated by Django 4.1.2 on 2023-07-22 12:31

import baby_food.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_number',
            field=models.PositiveBigIntegerField(validators=[baby_food.common.validators.validate_card_number]),
        ),
    ]
