# Generated by Django 4.1.2 on 2023-07-31 19:57

import baby_food.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_payments_card_expiry_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_holder',
            field=models.CharField(max_length=50, validators=[baby_food.common.validators.validate_name]),
        ),
    ]
