# Generated by Django 4.1.2 on 2023-08-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_remove_menu_name'),
        ('order', '0006_alter_payments_card_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menu'),
        ),
    ]
