# Generated by Django 4.1.2 on 2023-01-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_app', '0006_alter_menu_main_dish_and_more'),
        ('accounts', '0007_alter_child_options'),
        ('common', '0005_location_address_location_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.PositiveIntegerField(unique=True)),
                ('menu_type', models.CharField(choices=[('Allergy-Free', 'Allergy-Free'), ('With Allergens', 'With Allergens')], max_length=150)),
                ('menu_date', models.DateField()),
                ('age_range', models.CharField(blank=True, choices=[('10M-36M Allergy-Free', '10M-36M Allergy-Free'), ('10M-18M', '10M-18M'), ('18M-36M', '18M-36M')], max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=3.5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
                ('allergy_free_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_app.menuwithoutallergens')),
                ('allergy_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_app.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
