# Generated by Django 4.1.2 on 2023-01-29 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_category_options'),
        ('menu_app', '0004_alter_menu_price'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.menu')),
            ],
        ),
    ]
