# Generated by Django 4.1.2 on 2022-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
