# Generated by Django 4.1.2 on 2022-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dish_type', models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN_DISH', 'MAIN_DISH'), ('DESSERT', 'DESSERT')], max_length=10)),
                ('allergens', models.CharField(default='YES', editable=False, max_length=3)),
                ('ingredients', models.CharField(max_length=300)),
                ('weight', models.PositiveIntegerField(default=200, editable=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeWithoutAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dish_type', models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN_DISH', 'MAIN_DISH'), ('DESSERT', 'DESSERT')], max_length=10)),
                ('allergens', models.CharField(default='YES', editable=False, max_length=3)),
                ('ingredients', models.CharField(max_length=300)),
                ('weight', models.PositiveIntegerField(default=200, editable=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
