# Generated by Django 4.1.2 on 2023-01-24 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_category'),
        ('recipes', '0002_create_model_Recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='common.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.CharField(blank=True, default='YES', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN DISH', 'MAIN DISH'), ('DESSERT', 'DESSERT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=200, editable=False),
        ),
    ]
