# Generated by Django 4.1.2 on 2022-11-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_create_models_recipe_recipenoallergens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipewithoutallergens',
            options={'verbose_name_plural': 'Recipes Without Allergens'},
        ),
    ]
