# Generated by Django 4.1.2 on 2022-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_create_model_Recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeWithoutAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dish_type', models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN_DISH', 'MAIN_DISH'), ('DESSERT', 'DESSERT')], max_length=10)),
                ('allergens', models.CharField(default='YES', editable=False, max_length=3)),
                ('ingredients', models.CharField(max_length=300)),
                ('weight', models.PositiveIntegerField(default=200, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Recipes Without Allergens',
            },
        ),
    ]
