# Generated by Django 4.1.2 on 2022-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipewithoutallergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.CharField(blank=True, default='YES', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=200, editable=False),
        ),
        migrations.AlterField(
            model_name='recipewithoutallergens',
            name='allergens',
            field=models.CharField(blank=True, default='YES', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='recipewithoutallergens',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=200, editable=False),
        ),
    ]
