# Generated by Django 4.1.2 on 2023-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_category_alter_recipe_allergens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='allergens',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN DISH', 'MAIN DISH'), ('DESSERT', 'DESSERT'), ('AF SOUP', 'AF SOUP'), ('AF MAIN DISH', 'AF MAIN DISH'), ('AF DESSERT', 'AF DESSERT')], max_length=20),
        ),
    ]
