# Generated by Django 4.1.2 on 2022-12-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipewithoutallergens_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN DISH', 'MAIN DISH'), ('DESSERT', 'DESSERT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipewithoutallergens',
            name='dish_type',
            field=models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN DISH', 'MAIN DISH'), ('DESSERT', 'DESSERT')], max_length=10),
        ),
    ]
