# Generated by Django 4.1.2 on 2023-01-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN DISH', 'MAIN DISH'), ('DESSERT', 'DESSERT'), ('SOUP ALLERGY FREE ', 'SOUP ALLERGY FREE '), ('MAIN DISH ALLERGY FREE', 'MAIN DISH ALLERGY FREE'), ('DESSERT ALLERGY FREE', 'DESSERT ALLERGY FREE')], max_length=25),
        ),
    ]
