# Generated by Django 4.1.2 on 2023-01-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('SOUP', 'SOUP'), ('MAIN DISH', 'MAIN DISH'), ('DESSERT', 'DESSERT'), ('Allergy-Free SOUP', 'Allergy-Free SOUP'), ('Allergy-Free MAIN DISH', 'Allergy-Free MAIN DISH'), ('Allergy-Free DESSERT', 'Allergy-Free DESSERT')], max_length=25),
        ),
    ]
