# Generated by Django 4.1.2 on 2023-08-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-added_on']},
        ),
    ]
